---
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: "newsletter/accounts/1.0/user/signup"
          content-type: "application/json"
solace:
  java:
    host: tcp://localhost
    msgVpn: default
    clientUsername: default
    clientPassword: default
    connectRetries: -1
    reconnectRetries: -1
server:
  port: 9096
